import { create } from 'zustand';

export const useRestaurants = create(() => ({
  restaurants: [
    {
      id: '1',
      name: 'Confeitaria Colombo',
      address: 'R. Gonçalves Dias, 32 - Centro',
      lat: -22.9056,
      lng: -43.1783,
      menuItem: 'Coxinha de Frango e Pastel de Nata',
    },
    {
      id: '2',
      name: 'Amarelinho da Cinelândia',
      address: 'Praça Floriano, 55 - Centro',
      lat: -22.9115,
      lng: -43.1765,
      menuItem: 'Chopp gelado e Picanha fatiada',
    },
    {
      id: '3',
      name: 'Bar Luiz',
      address: 'R. da Carioca, 39 - Centro',
      lat: -22.9073,
      lng: -43.1802,
      menuItem: 'Salada de Batata com Salsichão',
    },
    {
      id: '4',
      name: 'Restaurante Mosteiro',
      address: 'R. São Bento, 13 - Centro',
      lat: -22.8996,
      lng: -43.1787,
      menuItem: 'Bacalhau à Gomes de Sá',
    },
    {
      id: '5',
      name: 'Beco do Rato',
      address: 'R. Joaquim Silva, 11 - Lapa/Centro',
      lat: -22.9142,
      lng: -43.1772,
      menuItem: 'Feijoada Completa',
    },
    {
      id: '6',
      name: 'Nova Capela',
      address: 'Av. Mem de Sá, 96 - Centro',
      lat: -22.9133,
      lng: -43.1818,
      menuItem: 'Cabrito Assado com Arroz de Brócolis',
    },
    {
      id: '7',
      name: 'Café do Bom, Cachaça da Boa',
      address: 'R. da Carioca, 10 - Centro',
      lat: -22.9075,
      lng: -43.1795,
      menuItem: 'Café Expresso e Cachaça Artesanal',
    },
    {
      id: '8',
      name: 'Lilia Restaurante',
      address: 'R. do Senado, 45 - Centro',
      lat: -22.9119,
      lng: -43.1834,
      menuItem: 'Menu Degustação do Chef',
    },
    {
      id: '9',
      name: 'Cervantes',
      address: 'Av. Almirante Barroso, Centro',
      lat: -22.9084,
      lng: -43.1751,
      menuItem: 'Sanduíche de Pernil com Abacaxi',
    },
    {
      id: '10',
      name: 'Rio Minho',
      address: 'R. do Ouvidor, 10 - Centro',
      lat: -22.9022,
      lng: -43.1752,
      menuItem: 'Sopa de Leão Veloso',
    },
  ],
}));
